name: CI

on:
  push:
    branches:
      - release/*

jobs:
  build:

    runs-on: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10
      - uses: actions/checkout@v1
      - name: Build the app
        run: |
          npm install
          electron-packager .
